main/urls.py
from django.urls import path
from . import views

app_name='main'
urlpatterns = [
    path('', views.home, name='home'),
    path('<int:id>', views.index, name='index'),
    path('create/', views.create,name='create'),
]

todo/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

class ToDoList(models.Model):
    name=models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Item(models.Model):
    todolist=models.ForeignKey(ToDoList, on_delete=models.CASCADE)
    text=models.CharField(max_length=400)
    complete=models.BooleanField()

    def __str__(self):
        return self.text

main/forms.py
from django import forms

class CreateNewList(forms.Form):
    name=forms.CharField(label="Name", max_length=100)
    check=forms.BooleanField(required=False)

main/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, HttpResponse
from .models import Item, ToDoList
from .forms import CreateNewList

# Create your views here.

def index(response, id):
    ls = ToDoList.objects.get(id=id)
    if response.method == "POST":
        print(response.POST)
        if response.POST.get("save"): #"save" is value of save button
            for item in ls.item_set.all(): #Saving checked Items
                if response.POST.get("c" + str(item.id)) == "clicked": #"clicked" is value of input
                    item.complete = True
                else:
                    item.complete = False
                item.save()
        elif response.POST.get("newItem"):#"newItem" is value of Add Item button
            txt = response.POST.get("new")#"new" is name of the input(Item which going to be added)
            if len(txt) > 2:
                ls.item_set.create(text=txt, complete=False)
            else:
                print("invalid")
    return render(response, "main/list.html", {"ls": ls})

def home(response):
	return render(response, "main/index.html", {'name':'test'})

def create(response):
    if response.method == "POST":
        form = CreateNewList(response.POST)
        if form.is_valid():
            n = form.cleaned_data["name"]
            t = ToDoList(name=n)
            t.save()
        return HttpResponseRedirect("/%i" %t.id)
    else:
        form = CreateNewList()
    return render(response, "main/create.html", {"form":form})

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block tittle %} ToDo App {% endblock %}</title>
    {% block head %} {% endblock %}
    <style type="text/css">
		.sidenav {
			height:100%;
			width:160px;
			position: fixed;
			z-index:1;
			top:0;
			left:0;
			background-color:#111;
            overflow-x: hidden;
			padding-top:20px;
		}
		.sidenav a {
			padding:6px 8px 6px 16px;
			text-decoration: none;
			font-size:25px;
			color: #818181;
			display:block;
		}
 
		.sidenav a:hover{
			color:#f1f1f1;
		}
		.main{
			margin-left:160px;
			padding: 0px 10px;
		}
 
	</style>
</head>
<body>
    <div class="sidenav">
        <a href="{% url 'main:home' %}">Home</a>
        <a href="{% url 'main:create' %}">Create</a>
        <a href="{% url 'main:' %}"></a>
    </div>
    <div id="content" name="content">
        {% block content %}

        {% endblock %}
    </div>

</body>
</html>

main/templates/main/create.html
{% extends 'main/base.html' %}
{% block title %}
Create New List
{% endblock %}
 
{% block content %}
	<h3>Create a New To Do List</h3>
	<br>
	<form method="POST" accept="main:create.html" >
		{% csrf_token %}
        {{ form.as_p }}
        <button type="submit", name="save">Create</button>
	</form>
{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %} Home {% endblock %}

main/templates/main/list.html
{% extends "main/base.html" %}
{% block title %}View List{% endblock %}
 
{% block content %}
    <h1>{{ls.name}}</h1>
    <form method="post" action="#">
    {% csrf_token %}
        <ul>
            {% for item in ls.item_set.all %}
                {% if item.complete == True %}
                    <li><input type="checkbox", value="clicked", name="c{{item.id}}" checked>{{item.text}}</li>
                {% else %}
                    <li><input type="checkbox", value="clicked", name="c{{item.id}}">{{item.text}}</li>
                {% endif %}
            {% endfor %}
        </ul>
        <button type="submit", name="newItem", value="newItem">Add Item</button>	
        <input type="text", name="new">
        <button type="submit", name="save", value="save">Save</button>
    </form>
{% endblock %}